"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel


class EditItemViewModelSaveRequest(BaseModel):
    context: str
    values: List[EditItemSaveValue]
    fill_action: Optional[AutoFillItemActionRequest]


