/**
 * Generated by typeshare 1.0.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class EditItemViewModelSaveRequest (
	var context: String,
	var values: List<EditItemSaveValue>,
	var fill_action: AutoFillItemActionRequest? = null
)

