"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from pydantic import BaseModel
from typing import List, Optional


class EditItemViewModelSaveRequest(BaseModel):
    context: str
    values: List[EditItemSaveValue]
    fill_action: Optional[AutoFillItemActionRequest]


