/**
 * Generated by typeshare 0.1.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class MyStruct (
	var a: Int,
	var c: Int
)

