/*
 Generated by typeshare 1.2.0
 */

import Foundation

public struct MyStruct: Codable {
	public let a: Int32
	public let c: Int32

	public init(a: Int32, c: Int32) {
		self.a = a
		self.c = c
	}
}
