/**
 * Generated by typeshare 1.1.0-prerelease02
 */
package com.agilebits

package object onepassword {

type AlsoString = String

type Uuid = String

// Unique identifier for an Account
type AccountUuid = Uuid

type ItemUuid = String

}
