/*
 Generated by typeshare 1.2.0
 */

import Foundation

public typealias AlsoString = String

public typealias Uuid = String

/// Unique identifier for an Account
public typealias AccountUuid = Uuid

public typealias ItemUuid = String
