/*
 Generated by typeshare 1.1.0
*/

export type AlsoString = string;

export type Uuid = string;

/** Unique identifier for an Account */
export type AccountUuid = Uuid;

export type ItemUuid = string;

