/**
 * Generated by typeshare 1.1.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

typealias AlsoString = String

typealias Uuid = String

/// Unique identifier for an Account
typealias AccountUuid = Uuid

typealias ItemUuid = String

