// Code generated by typeshare 1.2.0. DO NOT EDIT.
package proto

import "encoding/json"

type AlsoString string

type Uuid string

// Unique identifier for an Account
type AccountUuid Uuid

type ItemUuid string

