"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations




AlsoString = str


Uuid = str


ItemUuid = str


AccountUuid = Uuid


    """
    Unique identifier for an Account
    """
