/*
 Generated by typeshare 1.1.0-prerelease02
*/

/**
 * This is a comment.
 * Continued lovingly here
 */
export enum Colors {
	Red = "Red",
	Blue = "Blue",
	/** Green is a cool color */
	Green = "Green",
}

