// Code generated by typeshare 1.1.0. DO NOT EDIT.
package proto

import "encoding/json"

// This is a comment.
// Continued lovingly here
type Colors string
const (
	ColorsRed Colors = "Red"
	ColorsBlue Colors = "Blue"
	// Green is a cool color
	ColorsGreen Colors = "Green"
)
