/**
 * Generated by typeshare 1.1.0-prerelease02
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

typealias ItemId = String

/// Options that you could pick
typealias Options = String

