/**
 * Generated by typeshare 1.0.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

/// Generated type representing the anonymous struct variant `Anon` of the `SomeEnum` Rust enum
@Serializable
data class SomeEnumAnonInner (
	val the_field: SomeStruct
)

@Serializable
sealed class SomeEnum {
	@Serializable
	@SerialName("Unit")
	object Unit: SomeEnum()
	@Serializable
	@SerialName("Alg")
	data class Alg(val content: SomeStruct): SomeEnum()
	@Serializable
	@SerialName("Anon")
	data class Anon(val content: SomeEnumAnonInner): SomeEnum()
}

@Serializable
data class SomeStruct<T> (
	val some_field: SomeEnum,
	val some_special_field: List<HashMap<T, SomeEnum>?>
)

typealias SomeTypeAlias = SomeStruct<String>

