/*
 Generated by typeshare 1.1.0-prerelease02
 */

import Foundation

/// This is a comment.
/// Continued lovingly here
public enum Colors: String, Codable {
	case red
	case blue
	/// Green is a cool color
	case green = "green-like"
}
