/*
 Generated by typeshare 1.2.0
*/

/**
 * This is a comment.
 * Continued lovingly here
 */
export enum Colors {
	Red = "red",
	Blue = "blue",
	/** Green is a cool color */
	Green = "green-like",
}

