"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum


class Colors(str, Enum):
    """
    This is a comment.
    Continued lovingly here
    """
    RED = "red"
    BLUE = "blue"
    GREEN = "green-like"
    """
    Green is a cool color
    """
