[package]
name = "typeshare-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
heck = "0.5.0"
ignore = "0.4.23"
rayon = "1.10.0"
syn = { version = "2.0.96", features = ["full"] }
typeshare-model = { path = "../typeshare-model" }
