"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from pydantic import BaseModel
from typing import Literal


class SomeEnumA:
    type: Literal["A"]
class SomeEnumC(BaseModel):
    type: Literal["C"]
    content: int


SomeEnum = SomeEnumA | SomeEnumC

