"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel
from typing import Literal, Union


class SomeEnumTypes(str, Enum):
    A = "A"
    C = "C"

class SomeEnumA(BaseModel):
    SomeEnumTypes: Literal["A"] = "A"

class SomeEnumC(BaseModel):
    SomeEnumTypes: Literal["C"] = "C"
    content: int

SomeEnum = Union[SomeEnumA, SomeEnumC]
