"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import Literal
from pydantic import BaseModel


class SomeEnumA:
    type: Literal["A"]
class SomeEnumC(BaseModel):
    type: Literal["C"]
    content: int


SomeEnum = SomeEnumA | SomeEnumC

