/**
 * Generated by typeshare 0.1.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class QualifiedTypes (
	var unqualified: String,
	var qualified: String,
	var qualified_vec: List<String>,
	var qualified_hashmap: HashMap<String, String>,
	var qualified_optional: String? = null,
	var qualfied_optional_hashmap_vec: HashMap<String, List<String>>? = null
)

