"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel
from typing import Union


class AutofilledByUsInner(BaseModel):
    """
    Generated type representing the anonymous struct variant `Us` of the `AutofilledBy` Rust enum
    """
    uuid: str
    """
    The UUID for the fill
    """


class AutofilledBySomethingElseInner(BaseModel):
    """
    Generated type representing the anonymous struct variant `SomethingElse` of the `AutofilledBy` Rust enum
    """
    uuid: str
    """
    The UUID for the fill
    """


class AutofilledByTypes(str, Enum):
    US = "Us"
    SOMETHING_ELSE = "SomethingElse"

class AutofilledByUs(BaseModel):
    type: AutofilledByTypes = AutofilledByTypes.US
    content: AutofilledByUsInner

class AutofilledBySomethingElse(BaseModel):
    type: AutofilledByTypes = AutofilledByTypes.SOMETHING_ELSE
    content: AutofilledBySomethingElseInner

AutofilledBy = Union[AutofilledByUs, AutofilledBySomethingElse]
