"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from pydantic import BaseModel
from typing import Dict, List, Literal


class AdvancedColorsString(BaseModel):
    t: Literal["String"]
    c: str


class AdvancedColorsNumber(BaseModel):
    t: Literal["Number"]
    c: int


class AdvancedColorsNumberArray(BaseModel):
    t: Literal["NumberArray"]
    c: List[int]


class AdvancedColorsReallyCoolType(BaseModel):
    t: Literal["ReallyCoolType"]
    c: ItemDetailsFieldValue


class AdvancedColorsArrayReallyCoolType(BaseModel):
    t: Literal["ArrayReallyCoolType"]
    c: List[ItemDetailsFieldValue]


class AdvancedColorsDictionaryReallyCoolType(BaseModel):
    t: Literal["DictionaryReallyCoolType"]
    c: Dict[str, ItemDetailsFieldValue]


AdvancedColors = AdvancedColorsString | AdvancedColorsNumber | AdvancedColorsNumberArray | AdvancedColorsReallyCoolType | AdvancedColorsArrayReallyCoolType | AdvancedColorsDictionaryReallyCoolType

class ItemDetailsFieldValue(BaseModel):
    hello: str


