"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import List, Literal, Generic
from pydantic.generics import GenericModel
from pydantic import BaseModel


class GenericStructUsingGenericStruct(GenericModel, Generic[T]):
    struct_field: GenericStruct[str, T]
    second_struct_field: GenericStruct[T, str]
    third_struct_field: GenericStruct[T, List[T]]


class EnumUsingGenericStructVariantA:
    type: Literal["VariantA"]
    content: GenericStruct[str, float]


class EnumUsingGenericStructVariantB:
    type: Literal["VariantB"]
    content: GenericStruct[str, int]


class EnumUsingGenericStructVariantC:
    type: Literal["VariantC"]
    content: GenericStruct[str, bool]


class EnumUsingGenericStructVariantD:
    type: Literal["VariantD"]
    content: GenericStructUsingGenericStruct[None]


EnumUsingGenericStruct = EnumUsingGenericStructVariantA | EnumUsingGenericStructVariantB | EnumUsingGenericStructVariantC | EnumUsingGenericStructVariantD

class GenericStruct(GenericModel, Generic[A, B]):
    field_a: A
    field_b: List[B]


