"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from pydantic import BaseModel
from typing import Literal, List


class ItemDetailsFieldValue(BaseModel):
    """
    Struct comment
    """
    pass

class AdvancedColors2String(BaseModel):
    type: Literal["string"]
    content: str


class AdvancedColors2Number(BaseModel):
    type: Literal["number"]
    content: int


class AdvancedColors2NumberArray(BaseModel):
    type: Literal["number-array"]
    content: List[int]


class AdvancedColors2ReallyCoolType(BaseModel):
    type: Literal["really-cool-type"]
    content: ItemDetailsFieldValue


AdvancedColors2 = AdvancedColors2String | AdvancedColors2Number | AdvancedColors2NumberArray | AdvancedColors2ReallyCoolType

class AdvancedColorsString(BaseModel):
    type: Literal["String"]
    content: str


class AdvancedColorsNumber(BaseModel):
    type: Literal["Number"]
    content: int


class AdvancedColorsNumberArray(BaseModel):
    type: Literal["NumberArray"]
    content: List[int]


class AdvancedColorsReallyCoolType(BaseModel):
    type: Literal["ReallyCoolType"]
    content: ItemDetailsFieldValue


AdvancedColors = AdvancedColorsString | AdvancedColorsNumber | AdvancedColorsNumberArray | AdvancedColorsReallyCoolType
"""
Enum comment
"""

