"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import List, Literal
from pydantic import BaseModel


class ItemDetailsFieldValue(BaseModel):
    """
    Struct comment
    """
    pass

class AdvancedColors2String:
    type: Literal["string"]
    content: str


class AdvancedColors2Number:
    type: Literal["number"]
    content: int


class AdvancedColors2NumberArray:
    type: Literal["number-array"]
    content: List[int]


class AdvancedColors2ReallyCoolType:
    type: Literal["really-cool-type"]
    content: ItemDetailsFieldValue


AdvancedColors2 = AdvancedColors2String | AdvancedColors2Number | AdvancedColors2NumberArray | AdvancedColors2ReallyCoolType

class AdvancedColorsString:
    type: Literal["String"]
    content: str


class AdvancedColorsNumber:
    type: Literal["Number"]
    content: int


class AdvancedColorsNumberArray:
    type: Literal["NumberArray"]
    content: List[int]


class AdvancedColorsReallyCoolType:
    type: Literal["ReallyCoolType"]
    content: ItemDetailsFieldValue


AdvancedColors = AdvancedColorsString | AdvancedColorsNumber | AdvancedColorsNumberArray | AdvancedColorsReallyCoolType
"""
Enum comment
"""

