"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import Literal


class SomeEnumContext:
    type: Literal["Context"]
    content: str


class SomeEnumOther:
    type: Literal["Other"]
    content: int


SomeEnum = SomeEnumContext | SomeEnumOther

