"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Union


class SomeEnumTypes(str, Enum):
    CONTEXT = "Context"
    OTHER = "Other"

class SomeEnum(BaseModel):
    model_config = ConfigDict(use_enum_values=True)
    type: SomeEnumTypes
    content: Union[int, str]


    @classmethod
    def new_some_enum_context(cls, content : str):
        return cls(
            type=SomeEnumTypes.CONTEXT,
            content=content
        )


    @classmethod
    def new_some_enum_other(cls, content : int):
        return cls(
            type=SomeEnumTypes.OTHER,
            content=content
        )
