/*
 Generated by typeshare 1.1.0
*/

export type SomeEnum = 
	/** The associated String contains some opaque context */
	| { type: "Context", content: string }
	| { type: "Other", content: number };

