/**
 * Generated by typeshare 0.1.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
class CustomType

@Serializable
data class Types (
	var s: String,
	var static_s: String,
	var int8: Byte,
	var float: Float,
	var double: Double,
	var array: List<String>,
	var dictionary: HashMap<String, Int>,
	var optional_dictionary: HashMap<String, Int>? = null,
	var custom_type: CustomType
)

