/**
 * Generated by typeshare 1.1.0-prerelease02
 */
package com.agilebits

package object onepassword {

type UByte = Byte
type UShort = Short
type UInt = Int
type ULong = Int

}
package onepassword {

case class Foo (
	a: Long,
	b: ULong
)

}
