/**
 * Generated by typeshare 1.2.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

@Serializable
data class Foo (
	val a: Long,
	val b: ULong
)

