[typescript]
no-version-header = true

[typescript.type_mappings]
Url = "string"
DateTime = "string"

[kotlin]
package = "com.agilebits.onepassword"
no-version-header = true

[kotlin.type_mappings]
Url = "String"
DateTime = "String"

[swift]
no_version_header = true

[swift.type_mappings]
"Url" = "String"
"DateTime" = "Date"
