"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum


class Colors(str, Enum):
    """
    This is a comment.
    """
    RED = "red"
    BLUE = "blue-ish"
    GREEN = "Green"
