// Code generated by typeshare 0.1.0. DO NOT EDIT.
package proto

import "encoding/json"

// This is a comment.
type Colors string

const (
	ColorsRed   Colors = "red"
	ColorsBlue  Colors = "blue-ish"
	ColorsGreen Colors = "Green"
)
