/**
 * Generated by typeshare 1.0.0
 */
package com.agilebits

package object onepassword {

type UByte = Byte
type UShort = Short
type UInt = Int
type ULong = Int

}
package onepassword {

// This is a comment.
case class Foo (
	a: Byte,
	b: Short,
	c: Int,
	e: UByte,
	f: UShort,
	g: UInt
)

}
