/**
 * Generated by typeshare 1.0.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

/// This is a comment.
@Serializable
data class Foo (
	var a: Byte,
	var b: Short,
	var c: Int,
	var e: UByte,
	var f: UShort,
	var g: UInt
)

