// Code generated by typeshare 1.1.0-prerelease02. DO NOT EDIT.
package proto

import "encoding/json"

// This is a comment.
type Foo struct {
	A int `json:"a"`
	B int `json:"b"`
	C int `json:"c"`
	E int `json:"e"`
	F int `json:"f"`
	G uint32 `json:"g"`
}
