/**
 * Generated by typeshare 0.1.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

/// This is a Person struct with camelCase rename
@Serializable
data class Person (
	var firstName: String,
	var lastName: String,
	var age: UByte,
	var extraSpecialField1: Int,
	var extraSpecialField2: List<String>? = null
)

/// This is a Person2 struct with UPPERCASE rename
@Serializable
data class Person2 (
	var FIRST_NAME: String,
	var LAST_NAME: String,
	var AGE: UByte
)

