[package]
name = "typeshare-typescript"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
joinery = "3.1.0"
thiserror = "2.0.10"
typeshare-model = { path = "../../typeshare-model" }
