[package]
name = "typeshare-typescript"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
itertools = "0.14.0"
joinery = "3.1.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.10"
typeshare-model = { path = "../../model" }
