/**
 * Generated by typeshare 1.1.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

/// This is a comment.
@Serializable
enum class Colors(val string: String) {
	@SerialName("Red")
	Red("Red"),
	@SerialName("Blue")
	Blue("Blue"),
	@SerialName("Green")
	Green("Green"),
}

