/**
 * Generated by typeshare 1.1.0-prerelease02
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

typealias GenericTypeAlias<T> = List<T>

typealias NonGenericAlias = GenericTypeAlias<String?>

