/**
 * Generated by typeshare 1.1.0-prerelease02
 */
package com.agilebits

package object onepassword {

type GenericTypeAlias[T] = Vector[T]

type NonGenericAlias = GenericTypeAlias[Option[String]]

}
