"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import Annotated, Optional
from pydantic import BaseModel, Field


class Things(BaseModel):
    """
    This is a comment.
    """
    bla: str
    some_label: Annotated[Optional[str], Field(alias="label")]
    label_left: Annotated[Optional[str], Field(alias="label-left")]


