/**
 * Generated by typeshare 1.0.0
 */

@file:NoLiveLiterals

package com.agilebits.onepassword

import androidx.compose.runtime.NoLiveLiterals
import kotlinx.serialization.*

/// This is a comment.
@Serializable
data class Things (
	@SerialName("bla")
	var bla: String,
	@SerialName("label")
	var label: String? = null,
	@SerialName("label-left")
	var label_left: String? = null
)

