/**
 * Generated by typeshare 1.0.0
 */
package com.agilebits

package onepassword {

// This is a comment.
case class Things (
	bla: String,
	label: Option[String] = None,
	label_left: Option[String] = None
)

}
