/*
 Generated by typeshare 1.1.0-prerelease02
*/

/** This is a comment. */
export type Colors = 
	| { type: "Red", content?: undefined }
	| { type: "Blue", content?: undefined }
	| { type: "Green", content: string };

