"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import Literal


class ColorsRed:
    type: Literal["Red"]


class ColorsBlue:
    type: Literal["Blue"]


class ColorsGreen:
    type: Literal["Green"]
    content: str


Colors = ColorsRed | ColorsBlue | ColorsGreen
"""
This is a comment.
"""

