"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class StructHasVoidType(BaseModel):
    """
    This struct has a unit field
    """
    model_config = ConfigDict(populate_by_name=True)

    this_is_a_unit: None = Field(alias="thisIsAUnit")


class EnumHasVoidTypeTypes(str, Enum):
    HAS_A_UNIT = "hasAUnit"

class EnumHasVoidTypeHasAUnit(BaseModel):
    type: EnumHasVoidTypeTypes = EnumHasVoidTypeTypes.HAS_A_UNIT
    content: None

EnumHasVoidType = EnumHasVoidTypeHasAUnit
