"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel
from typing import Union


class AddressDetails(BaseModel):
    pass

class AddressTypes(str, Enum):
    FIXED_ADDRESS = "FixedAddress"
    NO_FIXED_ADDRESS = "NoFixedAddress"

class AddressFixedAddress(BaseModel):
    type: AddressTypes = AddressTypes.FIXED_ADDRESS
    content: AddressDetails

class AddressNoFixedAddress(BaseModel):
    type: AddressTypes = AddressTypes.NO_FIXED_ADDRESS

Address = Union[AddressFixedAddress, AddressNoFixedAddress]
