"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from pydantic import BaseModel
from typing import Literal, Union


class AddressDetails(BaseModel):
    pass
class AddressFixedAddress(BaseModel):
    AddressTypes: Literal["FixedAddress"] = "FixedAddress"
    content: AddressDetails

class AddressNoFixedAddress(BaseModel):
    AddressTypes: Literal["NoFixedAddress"] = "NoFixedAddress"

Address = Union[AddressFixedAddress, AddressNoFixedAddress]
