/*
 Generated by typeshare 1.1.0-prerelease02
*/

export interface AddressDetails {
}

export type Address = 
	| { type: "FixedAddress", content: AddressDetails }
	| { type: "NoFixedAddress", content?: undefined };

