use std::{
    collections::HashMap,
    io::{self, Write},
};

use itertools::Itertools;
use joinery::JoinableIterator;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use typeshare_model::{decorator::Value, prelude::*};

/// All information needed to generate Typescript type-code
#[derive(Default)]
pub struct TypeScript {
    /// Mappings from Rust type names to Typescript type names
    pub type_mappings: HashMap<TypeName, TypeName>,
    /// Whether or not to exclude the version header that normally appears at the top of generated code.
    /// If you aren't generating a snapshot test, this setting can just be left as a default (false)
    pub no_version_header: bool,
}

#[derive(Debug, Clone, Error)]
pub enum FormatTypeError {
    #[error("Can't have 64-bit or larger integers in typescript")]
    LargeInteger,

    #[error("Can't have generic types as map keys in typescript")]
    GenericMapKey,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct Config {
    type_mappings: HashMap<String, String>,
    no_version_header: bool,
}

impl Language<'_> for TypeScript {
    type FormatTypeError = FormatTypeError;

    type Config = Config;

    const NAME: &'static str = "typescript";

    fn new_from_config(config: Self::Config) -> anyhow::Result<Self> {
        Ok(Self {
            no_version_header: false,
            type_mappings: config
                .type_mappings
                .into_iter()
                .map(|(key, value)| (TypeName::new_string(key), TypeName::new_string(value)))
                .collect(),
        })
    }

    fn mapped_type(&self, type_name: &TypeName) -> Option<&TypeName> {
        self.type_mappings.get(type_name)
    }

    fn output_file_for_crate(&self, crate_name: &CrateName) -> String {
        // We could take care to output a correct camel case or snake case
        // or whatever typescript expects, but for now we won't bother.
        format!("typeshare_{crate_name}.ts")
    }

    fn format_special_type(
        &self,
        special_ty: &SpecialRustType,
        generic_context: &[TypeName],
    ) -> Result<String, FormatTypeError> {
        match special_ty {
            SpecialRustType::Vec(rtype) | SpecialRustType::Slice(rtype) => {
                Ok(format!("{}[]", self.format_type(rtype, generic_context)?))
            }
            SpecialRustType::Array(rtype, len) => {
                let formatted_type = self.format_type(rtype, generic_context)?;
                Ok(format!(
                    "[{}]",
                    std::iter::repeat(&formatted_type)
                        .take(*len)
                        .join_with(", ")
                ))
            }
            // We add optionality above the type formatting level
            SpecialRustType::Option(rtype) => self.format_type(rtype, generic_context),
            SpecialRustType::HashMap(rtype1, rtype2) => Ok(format!(
                "Record<{}, {}>",
                match rtype1.as_ref() {
                    RustType::Simple { id } if generic_context.contains(id) => {
                        return Err(FormatTypeError::GenericMapKey);
                    }
                    _ => self.format_type(rtype1, generic_context)?,
                },
                self.format_type(rtype2, generic_context)?
            )),
            SpecialRustType::Unit => Ok("undefined".into()),
            SpecialRustType::String => Ok("string".into()),
            SpecialRustType::Char => Ok("string".into()),
            SpecialRustType::I8
            | SpecialRustType::U8
            | SpecialRustType::I16
            | SpecialRustType::U16
            | SpecialRustType::I32
            | SpecialRustType::U32
            | SpecialRustType::I54
            | SpecialRustType::U53
            | SpecialRustType::F32
            | SpecialRustType::F64 => Ok("number".into()),
            SpecialRustType::Bool => Ok("boolean".into()),
            SpecialRustType::U64
            | SpecialRustType::I64
            | SpecialRustType::ISize
            | SpecialRustType::USize => Err(FormatTypeError::LargeInteger),
        }
    }

    fn begin_file(&self, w: &mut impl Write, _mode: FilesMode<&CrateName>) -> io::Result<()> {
        if !self.no_version_header {
            writeln!(w, "/*")?;
            writeln!(w, " Generated by typeshare {}", env!("CARGO_PKG_VERSION"))?;
            writeln!(w, "*/")?;
            writeln!(w)?;
        }
        Ok(())
    }

    fn write_imports(
        &self,
        w: &mut impl Write,
        _crate_name: &CrateName,
        imports: &ScopedCrateTypes<'_>,
    ) -> std::io::Result<()> {
        for (path, ty) in imports {
            write!(w, "import {{ ")?;
            let ty_list = ty.iter().join(", ");
            write!(w, "{ty_list}")?;
            writeln!(w, " }} from \"./{path}\";")?;
        }
        writeln!(w)
    }

    fn write_type_alias(&self, w: &mut impl Write, ty: &RustTypeAlias) -> io::Result<()> {
        self.write_comments(w, 0, &ty.comments)?;

        let r#type = self
            .format_type(&ty.r#type, ty.generic_types.as_slice())
            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;

        writeln!(
            w,
            "export type {}{} = {}{};\n",
            ty.id.renamed,
            (!ty.generic_types.is_empty())
                .then(|| format!("<{}>", ty.generic_types.join(", ")))
                .unwrap_or_default(),
            r#type,
            ty.r#type
                .is_optional()
                .then_some(" | undefined")
                .unwrap_or_default(),
        )?;

        Ok(())
    }

    fn write_struct(&self, w: &mut impl Write, rs: &RustStruct) -> io::Result<()> {
        self.write_comments(w, 0, &rs.comments)?;
        writeln!(
            w,
            "export interface {}{} {{",
            rs.id.renamed,
            (!rs.generic_types.is_empty())
                .then(|| format!("<{}>", rs.generic_types.join(", ")))
                .unwrap_or_default()
        )?;

        rs.fields
            .iter()
            .try_for_each(|f| self.write_field(w, f, &rs.generic_types))?;

        writeln!(w, "}}\n")
    }

    fn write_enum(&self, w: &mut impl Write, e: &RustEnum) -> io::Result<()> {
        self.write_comments(w, 0, &e.shared().comments)?;

        let generic_parameters = (!e.shared().generic_types.is_empty())
            .then(|| format!("<{}>", e.shared().generic_types.join(", ")))
            .unwrap_or_default();

        match e {
            RustEnum::Unit(shared) => {
                write!(
                    w,
                    "export enum {}{} {{",
                    shared.id.renamed, generic_parameters
                )?;

                self.write_enum_variants(w, e)?;

                writeln!(w, "\n}}\n")
            }
            RustEnum::Algebraic { shared, .. } => {
                write!(
                    w,
                    "export type {}{} = ",
                    shared.id.renamed, generic_parameters
                )?;

                self.write_enum_variants(w, e)?;

                write!(w, ";")?;
                writeln!(w)?;
                writeln!(w)
            }
        }
    }

    fn end_file(&self, _w: &mut impl Write) -> std::io::Result<()> {
        Ok(())
    }

    fn ignored_reference_types(&self) -> Vec<&str> {
        self.type_mappings.keys().map(|s| s.as_str()).collect()
    }
}

impl TypeScript {
    fn write_enum_variants(&self, w: &mut dyn Write, e: &RustEnum) -> io::Result<()> {
        match e {
            // Write all the unit variants out (there can only be unit variants in
            // this case)
            RustEnum::Unit(shared) => shared.variants.iter().try_for_each(|v| match v {
                RustEnumVariant::Unit(shared) => {
                    writeln!(w)?;
                    self.write_comments(w, 1, &shared.comments)?;
                    write!(
                        w,
                        "\t{} = {:?},",
                        shared.id.original,
                        &shared.id.renamed.as_str()
                    )
                }
                _ => unreachable!(),
            }),

            // Write all the algebraic variants out (all three variant types are possible
            // here)
            RustEnum::Algebraic {
                tag_key,
                content_key,
                shared,
            } => shared.variants.iter().try_for_each(|v| {
                writeln!(w)?;
                self.write_comments(w, 1, &v.shared().comments)?;
                match v {
                    RustEnumVariant::Unit(shared) => write!(
                        w,
                        "\t| {{ {}: {:?}, {}?: undefined }}",
                        tag_key,
                        shared.id.renamed.as_str(),
                        content_key
                    ),
                    RustEnumVariant::Tuple { ty, shared } => {
                        let r#type = self
                            .format_type(ty, e.shared().generic_types.as_slice())
                            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;
                        write!(
                            w,
                            "\t| {{ {}: {:?}, {}{}: {} }}",
                            tag_key,
                            shared.id.renamed.as_str(),
                            content_key,
                            ty.is_optional().then_some("?").unwrap_or_default(),
                            r#type
                        )
                    }
                    RustEnumVariant::AnonymousStruct { fields, shared } => {
                        writeln!(
                            w,
                            "\t| {{ {}: {:?}, {}: {{",
                            tag_key,
                            shared.id.renamed.as_str(),
                            content_key
                        )?;

                        fields.iter().try_for_each(|f| {
                            self.write_field(w, f, e.shared().generic_types.as_slice())
                        })?;

                        write!(w, "}}")?;
                        write!(w, "}}")
                    }
                }
            }),
        }
    }

    fn write_field(
        &self,
        w: &mut dyn Write,
        field: &RustField,
        generic_types: &[TypeName],
    ) -> io::Result<()> {
        self.write_comments(w, 1, &field.comments)?;
        let ts_ty = self
            .format_type(&field.ty, generic_types)
            .map_err(|e| io::Error::new(io::ErrorKind::Other, e))?;

        let optional = field.ty.is_optional() || field.has_default;
        let double_optional = field.ty.is_double_optional();
        let is_readonly = field
            .decorators
            .get("typescript")
            .map(|v| {
                v.iter()
                    .any(|dec| matches!(dec, Value::String(value) if value == "readonly"))
            })
            .unwrap_or(false);
        writeln!(
            w,
            "\t{}{}{}: {}{};",
            is_readonly.then_some("readonly ").unwrap_or_default(),
            typescript_property_aware_rename(field.id.renamed.as_str()),
            optional.then_some("?").unwrap_or_default(),
            ts_ty,
            double_optional.then_some(" | null").unwrap_or_default()
        )?;

        Ok(())
    }

    fn write_comments(
        &self,
        w: &mut dyn Write,
        indent: usize,
        comments: &[String],
    ) -> io::Result<()> {
        // Only attempt to write a comment if there are some, otherwise we're Ok()
        if !comments.is_empty() {
            let comment: String = {
                let tab_indent = "\t".repeat(indent);
                // If there's only one comment then keep it on the same line, otherwise we'll make a nice multi-line comment
                if comments.len() == 1 {
                    format!("{}/** {} */", tab_indent, comments.first().unwrap())
                } else {
                    let joined_comments = comments.join(&format!("\n{} * ", tab_indent));
                    format!(
                        "{tab}/**
{tab} * {comment}
{tab} */",
                        tab = tab_indent,
                        comment = joined_comments
                    )
                }
            };
            writeln!(w, "{}", comment)?;
        }
        Ok(())
    }
}

fn typescript_property_aware_rename(name: &str) -> String {
    if name.chars().any(|c| c == '-') {
        return format!("{:?}", name);
    }
    name.to_string()
}
