"""
 Generated by typeshare 1.0.0
"""
from __future__ import annotations

from typing import Literal
from pydantic import BaseModel


class OptionsRed(BaseModel):
    type: Literal["red"]
    content: bool


class OptionsBanana(BaseModel):
    type: Literal["banana"]
    content: str


class OptionsVermont(BaseModel):
    type: Literal["vermont"]
    content: Options


Options = OptionsRed | OptionsBanana | OptionsVermont

class MoreOptionsExactlyInner(BaseModel):
    """
    Generated type representing the anonymous struct variant `Exactly` of the `MoreOptions` Rust enum
    """
    config: str


class MoreOptionsBuiltInner(BaseModel):
    """
    Generated type representing the anonymous struct variant `Built` of the `MoreOptions` Rust enum
    """
    top: MoreOptions


class MoreOptionsNews(BaseModel):
    type: Literal["news"]
    content: bool


MoreOptions = MoreOptionsNews | MoreOptionsExactlyInner | MoreOptionsBuiltInner

