/*
 Generated by typeshare 1.1.0-prerelease02
*/

export type OptionalU32 = number | undefined;

export type OptionalU16 = number | undefined;

export interface FooBar {
	foo: OptionalU32;
	bar: OptionalU16;
}

