/**
 * Generated by typeshare 1.0.0
 */
package com.agilebits

package object onepassword {

type OptionalU32 = Option[UInt]

type OptionalU16 = Option[UShort]

}
package onepassword {

case class FooBar (
	foo: OptionalU32,
	bar: OptionalU16
)

}
