"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from pydantic import BaseModel
from typing import List, Literal, Union


class ArcyColors(BaseModel):
    """
    This is a comment.
    """
    red: int
    blue: str
    green: List[str]

class CellyColors(BaseModel):
    """
    This is a comment.
    """
    red: str
    blue: List[str]

class CowyColors(BaseModel):
    """
    This is a comment.
    """
    lifetime: str

class LockyColors(BaseModel):
    """
    This is a comment.
    """
    red: str

class MutexyColors(BaseModel):
    """
    This is a comment.
    """
    blue: List[str]
    green: str

class RcyColors(BaseModel):
    """
    This is a comment.
    """
    red: str
    blue: List[str]
    green: str

class BoxyColorsRed(BaseModel):
    BoxyColorsTypes: Literal["Red"] = "Red"

class BoxyColorsBlue(BaseModel):
    BoxyColorsTypes: Literal["Blue"] = "Blue"

class BoxyColorsGreen(BaseModel):
    BoxyColorsTypes: Literal["Green"] = "Green"
    content: str

"""
This is a comment.
"""
BoxyColors = Union[BoxyColorsRed, BoxyColorsBlue, BoxyColorsGreen]
