"""
 Generated by typeshare 1.12.0
"""
from __future__ import annotations

from enum import Enum
from pydantic import BaseModel
from typing import List, Union


class ArcyColors(BaseModel):
    """
    This is a comment.
    """
    red: int
    blue: str
    green: List[str]


class CellyColors(BaseModel):
    """
    This is a comment.
    """
    red: str
    blue: List[str]


class CowyColors(BaseModel):
    """
    This is a comment.
    """
    lifetime: str


class LockyColors(BaseModel):
    """
    This is a comment.
    """
    red: str


class MutexyColors(BaseModel):
    """
    This is a comment.
    """
    blue: List[str]
    green: str


class RcyColors(BaseModel):
    """
    This is a comment.
    """
    red: str
    blue: List[str]
    green: str


class BoxyColorsTypes(str, Enum):
    RED = "Red"
    BLUE = "Blue"
    GREEN = "Green"

class BoxyColorsRed(BaseModel):
    type: BoxyColorsTypes = BoxyColorsTypes.RED

class BoxyColorsBlue(BaseModel):
    type: BoxyColorsTypes = BoxyColorsTypes.BLUE

class BoxyColorsGreen(BaseModel):
    type: BoxyColorsTypes = BoxyColorsTypes.GREEN
    content: str

BoxyColors = Union[BoxyColorsRed, BoxyColorsBlue, BoxyColorsGreen]
